#page title
page_title                                : Zen Symmetry                                       # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.eighthbitlab.symmetry                                          # Enter Google Play Store URL.
presskit_download_link                    :                                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Zen Symmetry - Relaxing Puzzles                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Sharpens focus, trains brain! Relaxing, zen game. Place tiles symmetrically

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Pavel Silin                               
your_link                                 : https://8tbl.github.io/                     
your_city                                 : Russia, Saint-Petersburg                                
email_address                             : 8thBitLab@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Relaxing puzzles for your mind
    description                           : Zen Symmetry is a game designed to help you take a break from the hustle and bustle, calm down and develop your mind.
    fontawesome_icon_name                 : star
    
  - title                                 : Challenge along with a calming and relaxing atmosphere
    description                           : The main idea of ​​this brain teaser is very simple, you need to solve logic puzzles to create symmetrical images around the lines and centers on the field.
    fontawesome_icon_name                 : star


  - title                                 : A lot of puzzles with multiple features
    description                           : The game has 4 chapters, each with multiple complexity levels. The chapters aren't only set apart by their complexity levels but they also have their own distinctive features.
    fontawesome_icon_name                 : star
    
  - title                                 : Puzzle retreat, indeed!
    description                           : Try Zen mode, this is the most comfortable mode for playing, when you just want to relax and rest, the levels are generated endlessly, gradually, and unobtrusively increasing their difficulty.
    fontawesome_icon_name                 : star
    

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#000000"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#000000"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
